/*Creación de tablas*/

-- MAESTRAS
CREATE TABLE LAFT.TBL_MAE_APLICACION(
    NID NUMBER PRIMARY KEY,
    SDESCRIPCION VARCHAR2(100),
    DREGISTRO DATE,
    SUSUARIO VARCHAR(30),
    NESTADO NUMBER(1)
);

CREATE TABLE LAFT.TBL_MAE_DOCUMENTO(
    NID NUMBER PRIMARY KEY,
    SDESCRIPCION VARCHAR2(100),
    DREGISTRO DATE,
    SUSUARIO VARCHAR(30),
    NESTADO NUMBER(1)
);

CREATE TABLE LAFT.TBL_MAE_PAIS(
    NID NUMBER PRIMARY KEY,
    SDESCRIPCION VARCHAR2(100),
    DREGISTRO DATE,
    SUSUARIO VARCHAR(30),
    NESTADO NUMBER(1)
);

CREATE TABLE LAFT.TBL_MAE_PERSONA(
    NID NUMBER PRIMARY KEY,
    SDESCRIPCION VARCHAR2(100),
    DREGISTRO DATE,
    SUSUARIO VARCHAR(30),
    NESTADO NUMBER(1)
);

CREATE TABLE LAFT.TBL_MAE_PRODUCTO(
    NID NUMBER PRIMARY KEY,
    SDESCRIPCION VARCHAR2(100),
    DREGISTRO DATE,
    SUSUARIO VARCHAR(30),
    NESTADO NUMBER(1)
);

CREATE TABLE LAFT.TBL_MAE_SENIAL(
    NID NUMBER PRIMARY KEY,
    SDESCRIPCION VARCHAR2(100),
	SCOLOR VARCHAR2(20),
    DREGISTRO DATE,
    SUSUARIO VARCHAR(30),
    NESTADO NUMBER(1)
);


-- CONFIGURACIONES
CREATE TABLE LAFT.TBL_CFG_SENIAL_APP(
    NID           NUMBER PRIMARY KEY,
    NIDSENIAL     NUMBER,
    NIDAPLICACION NUMBER,
    DREGISTRO     DATE,
    SUSUARIO      VARCHAR2(30),
    NESTADO       NUMBER(1),
    CONSTRAINT I1_TBL_CFG_SENIAL_APP UNIQUE(NIDSENIAL,NIDAPLICACION)
);

CREATE TABLE LAFT.TBL_CFG_SENIAL_APP_PROD(
    NID          NUMBER PRIMARY KEY,
    NIDSENIALAPP NUMBER,
    NIDPRODUCTO  NUMBER,
    DREGISTRO    DATE,
    SUSUARIO     VARCHAR2(30),
    NESTADO      NUMBER(1),
	CONSTRAINT FK_NIDSENIALAPP FOREIGN KEY (NIDSENIALAPP) REFERENCES LAFT.TBL_CFG_SENIAL_APP(NID)
);

CREATE TABLE LAFT.TBL_CFG_REGISTRO_APP(
    NID           NUMBER PRIMARY KEY,
    NIDREGISTRO   NUMBER,
    NIDAPLICACION NUMBER,
    DREGISTRO     DATE,
    SUSUARIO      VARCHAR2(30),
    NESTADO       NUMBER(1)
);

CREATE TABLE LAFT.TBL_CFG_REGISTRO_APP_PROD(
    NID             NUMBER PRIMARY KEY,
    NIDREGISTROAPP  NUMBER,
    NIDPRODUCTO     NUMBER,
    DREGISTRO       DATE,
    SUSUARIO        VARCHAR2(30),
    NESTADO         NUMBER(1),
	CONSTRAINT FK_NIDREGISTROAPP FOREIGN KEY (NIDREGISTROAPP) REFERENCES LAFT.TBL_CFG_REGISTRO_APP(NID)
);


-- TRANSACCIONES
CREATE TABLE LAFT.TBL_TRX_CARGA(
    NID NUMBER PRIMARY KEY,
    DREGISTRO DATE,
    SUSUARIO VARCHAR2(30),
    NESTADO NUMBER(1)
);

CREATE TABLE LAFT.TBL_TRX_REGISTRO(
    NID NUMBER PRIMARY KEY,
    NSEQ NUMBER,
    SNUMERO VARCHAR2(10),
    NIDCARGA NUMBER,
    NIDPERSONA NUMBER,
    SPERSONA VARCHAR2(50),
    NIDPAIS NUMBER,
    SPAIS VARCHAR2(50),
    NIDSENIAL NUMBER,
    SSENIAL VARCHAR2(50),
    NIDDOCUMENTO NUMBER,
    SDOCUMENTO VARCHAR2(150),
    SNUMDOC VARCHAR2(30),
    SAPEPAT VARCHAR2(50),
    SAPEMAT VARCHAR2(50),
    SNOMBRE VARCHAR2(150),
    SOBSERVACION VARCHAR2(255),
    DREGISTRO DATE,
    SUSUARIO VARCHAR2(30),
    NESTADO NUMBER(1),
	NEDITADO NUMBER(1),
    CONSTRAINT FK_NIDCARGA FOREIGN KEY (NIDCARGA) REFERENCES LAFT.TBL_TRX_CARGA (NID)
);


-- HISTORICAS
CREATE TABLE LAFT.TBL_HIS_CARGA(
    NID       NUMBER,
    DREGISTRO DATE,
    SUSUARIO  VARCHAR2(30),
    NESTADO   NUMBER(1),
    SUSERDB   VARCHAR2(30) NOT NULL,
    SUSERPC   VARCHAR2(50) NOT NULL,
    SIP       VARCHAR2(15) NOT NULL,
    SHOST     VARCHAR2(50) NOT NULL,
    DREGHIS   DATE NOT NULL,
    STIPHIS   CHAR(1) NOT NULL
);

CREATE TABLE LAFT.TBL_HIS_REGISTRO(
    NID NUMBER,
    NSEQ NUMBER,
    SNUMERO VARCHAR2(10),
    NIDCARGA NUMBER,
    NIDPERSONA NUMBER,
    SPERSONA VARCHAR2(50),
    NIDPAIS NUMBER,
    SPAIS VARCHAR2(50),
    NIDSENIAL NUMBER,
    SSENIAL VARCHAR2(50),
    NIDDOCUMENTO NUMBER,
    SDOCUMENTO VARCHAR2(150),
    SNUMDOC VARCHAR2(30),
    SAPEPAT VARCHAR2(50),
    SAPEMAT VARCHAR2(50),
    SNOMBRE VARCHAR2(150),
    SOBSERVACION VARCHAR2(255),
    DREGISTRO DATE,
    SUSUARIO VARCHAR2(30),
    NESTADO   NUMBER(1),
	NEDITADO NUMBER(1),
    SUSERDB   VARCHAR2(30) NOT NULL,
    SUSERPC   VARCHAR2(50) NOT NULL,
    SIP       VARCHAR2(15) NOT NULL,
    SHOST     VARCHAR2(50) NOT NULL,
    DREGHIS   DATE NOT NULL,
    STIPHIS   CHAR(1) NOT NULL
);


/* INDICES */
CREATE INDEX LAFT.IDX01_TBL_TRX_REGISTRO ON LAFT.TBL_TRX_REGISTRO(NSEQ);
CREATE INDEX LAFT.IDX02_TBL_TRX_REGISTRO ON LAFT.TBL_TRX_REGISTRO(SNUMERO);
CREATE INDEX LAFT.IDX03_TBL_TRX_REGISTRO ON LAFT.TBL_TRX_REGISTRO(SNUMDOC);
CREATE INDEX LAFT.IDX04_TBL_TRX_REGISTRO ON LAFT.TBL_TRX_REGISTRO(SNOMBRE);
CREATE INDEX LAFT.IDX01_TBL_HIS_CARGA ON LAFT.TBL_HIS_CARGA(NID);
CREATE INDEX LAFT.IDX02_TBL_HIS_CARGA ON LAFT.TBL_HIS_CARGA(DREGHIS);
CREATE INDEX LAFT.IDX01_TBL_HIS_REGISTRO ON LAFT.TBL_HIS_REGISTRO(NID);
CREATE INDEX LAFT.IDX02_TBL_HIS_REGISTRO ON LAFT.TBL_HIS_REGISTRO(NSEQ);
CREATE INDEX LAFT.IDX03_TBL_HIS_REGISTRO ON LAFT.TBL_HIS_REGISTRO(DREGHIS);
CREATE INDEX LAFT.IDX04_TBL_HIS_REGISTRO ON LAFT.TBL_HIS_REGISTRO(NIDCARGA);

-- SECUENCIAS
CREATE SEQUENCE LAFT.SEQ_TBL_TRX_CARGA;
CREATE SEQUENCE LAFT.SEQ_TBL_TRX_REGISTRO;
CREATE SEQUENCE LAFT.SEQ_TBL_CFG_SENIAL_APP;
CREATE SEQUENCE LAFT.SEQ_TBL_CFG_SENIAL_APP_PROD;
CREATE SEQUENCE LAFT.SEQ_TBL_CFG_REGISTRO_APP;
CREATE SEQUENCE LAFT.SEQ_TBL_CFG_REGISTRO_APP_PROD;

