namespace protecta.laft.api.DTO {
    public class SbsReportEnity {
        public string NPERIODO_PROCESO {get; set;}
        public string NIDREGIMEN {get;set;}
        public string NIDALERTA {get; set;}

        public string FILA {get; set;}
        public string OPERACION {get; set;}
        public string OFICINA {get; set;}
        public string INTERNO {get; set;}
        public string MODALIDAD {get; set;}
        public string OPE_UBIGEO {get; set;}
        public string OPE_FECHA {get; set;}
        public string OPE_HORA {get; set;}
        public string EJE_RELACION {get; set;}
        public string EJE_CONDICION {get; set;}
        public string EJE_TIPPER {get; set;}
        public string EJE_TIPDOC {get; set;}
        public string EJE_NUMDOC {get; set;}
        public string EJE_NUMRUC {get; set;}
        public string EJE_APEPAT {get; set;}
        public string EJE_APEMAT {get; set;}
        public string EJE_NOMBRES {get; set;}
        public string EJE_OCUPACION {get; set;}
        public string EJE_PAIS {get; set;}
        public string EJE_CARGO {get; set;}
        public string EJE_PEP {get; set;}
        public string EJE_DOMICILIO {get; set;}
        public string EJE_DEPART {get; set;}
        public string EJE_PROV {get; set;}
        public string EJE_DIST {get; set;}
        public string EJE_TELEFONO {get; set;}
        public string ORD_RELACION {get; set;}
        public string ORD_CONDICION {get; set;}
        public string ORD_TIPPER {get; set;}
        public string ORD_TIPDOC {get; set;}
        public string ORD_NUMDOC {get; set;}
        public string ORD_NUMRUC {get; set;}
        public string ORD_APEPAT {get; set;}
        public string ORD_APEMAT {get; set;}
        public string ORD_NOMBRES {get; set;}
        public string ORD_OCUPACION {get; set;}
        public string ORD_PAIS {get; set;}
        public string ORD_CARGO {get; set;}
        public string ORD_PEP {get; set;}
        public string ORD_DOMICILIO {get; set;}
        public string ORD_DEPART {get; set;}
        public string ORD_PROV {get; set;}
        public string ORD_DIST {get; set;}
        public string ORD_TELEFONO {get; set;}
        public string BEN_RELACION {get; set;}
        public string BEN_CONDICION {get; set;}
        public string BEN_TIP_PER {get; set;}
        public string BEN_TIP_DOC {get; set;}
        public string BEN_NUM_DOC {get; set;}
        public string BEN_NUM_RUC {get; set;}
        public string BEN_APEPAT {get; set;}
        public string BEN_APEMAT {get; set;}
        public string BEN_NOMBRES {get; set;}
        public string BEN_OCUPACION {get; set;}
        public string BEN_PAIS {get; set;}
        public string BEN_CARGO {get; set;}
        public string BEN_PEP {get; set;}
        public string BEN_DOMICILIO {get; set;}
        public string BEN_DEPART {get; set;}
        public string BEN_PROV {get; set;}
        public string BEN_DIST {get; set;}
        public string BEN_TELEFONO {get; set;}
        public string DAT_TIPFON {get; set;}
        public string DAT_TIPOPE {get; set;}
        public string DAT_DESOPE {get; set;}
        public string DAT_ORIFON {get; set;}
        public string DAT_MONOPE {get; set;}
        public string DAT_MONOPE_A {get; set;}
        public string DAT_MTOOPE {get; set;}
        public string DAT_MTOOPEA {get; set;}
        public string DAT_COD_ENT_INVO {get; set;}
        public string DAT_COD_TIP_CTAO {get; set;}
        public string DAT_COD_CTAO {get; set;}
        public string DAT_ENT_FNC_EXTO {get; set;}
        public string DAT_COD_ENT_INVB {get; set;}
        public string DAT_COD_TIP_CTAB {get; set;}
        public string DAT_COD_CTAB {get; set;}
        public string DAT_ENT_FNC_EXTB {get; set;}
        public string DAT_ALCANCE {get; set;}
        public string DAT_COD_PAISO {get; set;}
        public string DAT_COD_PAISD {get; set;}
        public string DAT_INTOPE {get; set;}
        public string DAT_FORMA {get; set;}
        public string DAT_INFORM {get; set;}

    }
}
